[package]
name = "DeepBookRouter"
edition = "2024.beta"

[dependencies]
deepbook = { local = "../../deepbookv3/packages/deepbook", addr_subst = { deepbook = "0x2c8d603bc51326b8c13cef9dd07031a408a48dddb541963357661df5d3204809" } }

[addresses]
router = "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
