[package]
name = "DeepBookRouter"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.64.2", override = true }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "mainnet-v1.64.2", override = true }
deepbook = { local = "../../deepbookv3/packages/deepbook" }

[addresses]
router = "0x0"
